update to dev only

diff --git a/app/Dockerfile b/app/Dockerfile
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -1,5 +1,156 @@
-### Make base stage as production ###
-FROM vasymus/base-php-nginx-node:php-8.0.12-nginx-1.20.1-node-14.18.1 as base
+FROM php:5.6.40-fpm-alpine3.8 as base
+
+LABEL maintainer="NGINX Docker Maintainers <docker-maint@nginx.com>"
+
+ENV NGINX_VERSION 1.14.1
+
+RUN GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \
+	&& CONFIG="\
+		--prefix=/etc/nginx \
+		--sbin-path=/usr/sbin/nginx \
+		--modules-path=/usr/lib/nginx/modules \
+		--conf-path=/etc/nginx/nginx.conf \
+		--error-log-path=/var/log/nginx/error.log \
+		--http-log-path=/var/log/nginx/access.log \
+		--pid-path=/var/run/nginx.pid \
+		--lock-path=/var/run/nginx.lock \
+		--http-client-body-temp-path=/var/cache/nginx/client_temp \
+		--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
+		--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
+		--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
+		--http-scgi-temp-path=/var/cache/nginx/scgi_temp \
+		--user=nginx \
+		--group=nginx \
+		--with-http_ssl_module \
+		--with-http_realip_module \
+		--with-http_addition_module \
+		--with-http_sub_module \
+		--with-http_dav_module \
+		--with-http_flv_module \
+		--with-http_mp4_module \
+		--with-http_gunzip_module \
+		--with-http_gzip_static_module \
+		--with-http_random_index_module \
+		--with-http_secure_link_module \
+		--with-http_stub_status_module \
+		--with-http_auth_request_module \
+		--with-http_xslt_module=dynamic \
+		--with-http_image_filter_module=dynamic \
+		--with-http_geoip_module=dynamic \
+		--with-threads \
+		--with-stream \
+		--with-stream_ssl_module \
+		--with-stream_ssl_preread_module \
+		--with-stream_realip_module \
+		--with-stream_geoip_module=dynamic \
+		--with-http_slice_module \
+		--with-mail \
+		--with-mail_ssl_module \
+		--with-compat \
+		--with-file-aio \
+		--with-http_v2_module \
+	" \
+	&& addgroup -S nginx \
+	&& adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx \
+	&& apk add --no-cache --virtual .build-deps \
+		gcc \
+		libc-dev \
+		make \
+		openssl-dev \
+		pcre-dev \
+		zlib-dev \
+		linux-headers \
+		curl \
+		gnupg1 \
+		libxslt-dev \
+		gd-dev \
+		geoip-dev \
+	&& curl -fSL https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o nginx.tar.gz \
+	&& curl -fSL https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz.asc  -o nginx.tar.gz.asc \
+	&& export GNUPGHOME="$(mktemp -d)" \
+	&& found=''; \
+	for server in \
+		ha.pool.sks-keyservers.net \
+		hkp://keyserver.ubuntu.com:80 \
+		hkp://p80.pool.sks-keyservers.net:80 \
+		pgp.mit.edu \
+	; do \
+		echo "Fetching GPG key $GPG_KEYS from $server"; \
+		gpg --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$GPG_KEYS" && found=yes && break; \
+	done; \
+	test -z "$found" && echo >&2 "error: failed to fetch GPG key $GPG_KEYS" && exit 1; \
+	gpg --batch --verify nginx.tar.gz.asc nginx.tar.gz \
+	&& rm -rf "$GNUPGHOME" nginx.tar.gz.asc \
+	&& mkdir -p /usr/src \
+	&& tar -zxC /usr/src -f nginx.tar.gz \
+	&& rm nginx.tar.gz \
+	&& cd /usr/src/nginx-$NGINX_VERSION \
+	&& ./configure $CONFIG --with-debug \
+	&& make -j$(getconf _NPROCESSORS_ONLN) \
+	&& mv objs/nginx objs/nginx-debug \
+	&& mv objs/ngx_http_xslt_filter_module.so objs/ngx_http_xslt_filter_module-debug.so \
+	&& mv objs/ngx_http_image_filter_module.so objs/ngx_http_image_filter_module-debug.so \
+	&& mv objs/ngx_http_geoip_module.so objs/ngx_http_geoip_module-debug.so \
+	&& mv objs/ngx_stream_geoip_module.so objs/ngx_stream_geoip_module-debug.so \
+	&& ./configure $CONFIG \
+	&& make -j$(getconf _NPROCESSORS_ONLN) \
+	&& make install \
+	&& rm -rf /etc/nginx/html/ \
+	&& mkdir /etc/nginx/conf.d/ \
+	&& mkdir -p /usr/share/nginx/html/ \
+	&& install -m644 html/index.html /usr/share/nginx/html/ \
+	&& install -m644 html/50x.html /usr/share/nginx/html/ \
+	&& install -m755 objs/nginx-debug /usr/sbin/nginx-debug \
+	&& install -m755 objs/ngx_http_xslt_filter_module-debug.so /usr/lib/nginx/modules/ngx_http_xslt_filter_module-debug.so \
+	&& install -m755 objs/ngx_http_image_filter_module-debug.so /usr/lib/nginx/modules/ngx_http_image_filter_module-debug.so \
+	&& install -m755 objs/ngx_http_geoip_module-debug.so /usr/lib/nginx/modules/ngx_http_geoip_module-debug.so \
+	&& install -m755 objs/ngx_stream_geoip_module-debug.so /usr/lib/nginx/modules/ngx_stream_geoip_module-debug.so \
+	&& ln -s ../../usr/lib/nginx/modules /etc/nginx/modules \
+	&& strip /usr/sbin/nginx* \
+	&& strip /usr/lib/nginx/modules/*.so \
+	&& rm -rf /usr/src/nginx-$NGINX_VERSION \
+	\
+	# Bring in gettext so we can get `envsubst`, then throw
+	# the rest away. To do this, we need to install `gettext`
+	# then move `envsubst` out of the way so `gettext` can
+	# be deleted completely, then move `envsubst` back.
+	&& apk add --no-cache --virtual .gettext gettext \
+	&& mv /usr/bin/envsubst /tmp/ \
+	\
+	&& runDeps="$( \
+		scanelf --needed --nobanner --format '%n#p' /usr/sbin/nginx /usr/lib/nginx/modules/*.so /tmp/envsubst \
+			| tr ',' '\n' \
+			| sort -u \
+			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
+	)" \
+	&& apk add --no-cache --virtual .nginx-rundeps $runDeps \
+	&& apk del .build-deps \
+	&& apk del .gettext \
+	&& mv /tmp/envsubst /usr/local/bin/ \
+	\
+	# Bring in tzdata so users could set the timezones through the environment
+	# variables
+	&& apk add --no-cache tzdata \
+	\
+	# forward request and error logs to docker log collector
+	&& ln -sf /dev/stdout /var/log/nginx/access.log \
+	&& ln -sf /dev/stderr /var/log/nginx/error.log
+
+# install composer from official image @see https://hub.docker.com/_/composer
+COPY --from=composer:1.10.25 /usr/bin/composer /usr/bin/composer
+
+### / PREPARATION PART of image ###
+
+
+RUN apk update && apk add \
+    openssh \
+    dos2unix \
+    bash \
+    supervisor \
+    curl \
+    zip \
+    unzip \
+    ca-certificates
 
 # add bitbucket and github to known hosts for ssh needs
 WORKDIR /root/.ssh
@@ -7,13 +158,6 @@ RUN chmod 0600 /root/.ssh \
     && ssh-keyscan -t rsa bitbucket.org >> known_hosts \
     && ssh-keyscan -t rsa github.com >> known_hosts \
     && ssh-keyscan -t rsa gitlab.com >> known_hosts
-
-# packages that will be used in a docker or in project via `exec()` php function @see https://www.php.net/manual/ru/function.exec.php
-#RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y \
-#    gettext-base \
-#    dos2unix \
-#    wget \
-#    && rm -rf /var/lib/apt/lists/*
 
 # add custom php-fpm pool settings, these get written at entrypoint startup
 ENV FPM_PM_MAX_CHILDREN=20 \
@@ -44,18 +188,6 @@ COPY ./docker/app/nginx-site.conf /tmp/nginx-site.conf
 RUN mkdir -p /etc/nginx/conf.d \
     && envsubst '$FPM_PING_URI $FPM_STATUS_URI $NGINX_STATUS_URI $NGINX_READ_TIMEOUT' < /tmp/nginx-site.conf > /etc/nginx/conf.d/default.conf
 
-# Dockerfile private variable -- not for build
-ARG __PATH=$PATH
-
-ENV COMPOSER_VENDOR_DIR="/var/www/html/vendor" \
-    PATH="/var/www/html/node_modules/.bin:$__PATH"
-
-### Decided to move `composer install` and `npm install` only to `test` and `prod` stages [but not on `dev`]
-### Think it's more convenient for developer to execute
-### docker-compose exec app bash
-### and run according comands locally
-
-
 
 ### dev stage ###
 FROM base as dev
@@ -78,164 +210,12 @@ ENV NODE_ENV="development"
 # 9003 - for php debug
 EXPOSE 80 9003
 
-## no need in `dev` stage to run `COPY --chown=www-data:www-data . .` because in dev
-## we will bind mount whole project (@see docker-compose.yml:services.app.volumes)
 
 ### copy entrypoint ###
 COPY ./docker/app/docker-php-entrypoint-dev /usr/local/bin/
 RUN dos2unix /usr/local/bin/docker-php-entrypoint-dev \
     && chmod 770 /usr/local/bin/docker-php-entrypoint-dev
 
-# for running some scripts as www-data inside container
-RUN apt-get update && apt-get install -y sudo
-
-##
-## Configuration of supervisord, php and nginx
-##
 # supervisord config
 COPY ./docker/app/supervisord.conf /etc/supervisord.conf
-
-
-### dependencies stage ###
-# for running installing non-dev dependencies of composer and npm ###
-FROM base as dependencies
-
-# exclude packages from autoremove that are used @see https://askubuntu.com/a/943292
-#RUN apt-mark manual dos2unix supervisor wget openssh-client ca-certificates nginx
-#RUN apt-get remove --purge --auto-remove -y -o APT::AutoRemove::RecommendsImportant=false
-
-# in laravel `env()` function take environemt variables from .env file or from OS global environment
-# in production we put all environments to OS global environment:
-# either in docker-stack.yml services.app.environment or here
-# in dev we assume that developer manually create .env file (based on .env.example)
-ENV APP_ENV="production" \
-    APP_DEBUG="false" \
-    APP_URL="http://localhost" \
-    # errors in docker should go to stdout (not in file, because the file could consume all space on disk)
-    LOG_CHANNEL="errorlog" \
-    LOG_LEVEL="debug" \
-    DB_CONNECTION="mysql" \
-    DB_PORT=3306 \
-    BROADCAST_DRIVER="log" \
-    SESSION_LIFETIME=120
-
-### decided not to put dependencies in another dir (for now), because it would require to change accordingly ./public/index.php and ./artisan
-WORKDIR /var/www/html
-
-##
-## Compose Package Manager
-##
-COPY --chown=www-data:www-data ./composer.json ./composer.lock* ./
-# RUN composer config github-oauth.github.com YOUROAUTHKEYHERE
-RUN composer install --no-scripts --no-autoloader --ansi --no-interaction --no-dev
-##
-## Node Build Tools
-##
-ENV NODE_ENV="production"
-COPY --chown=www-data:www-data package*.json ./
-RUN npm config list \
-    # is better then `npm install` for production
-    && npm ci || npm install
-ENV PATH="/var/www/htmls/node_modules/.bin:$__PATH"
-
-
-
-### test stage ###
-FROM dependencies as test
-
-WORKDIR /var/www/html
-
-##
-## Compose Package Manager
-##
-# RUN composer config github-oauth.github.com YOUROAUTHKEYHERE
-# didn't found composer analogue for 'npm install --only=production'
-RUN composer install --no-scripts --no-autoloader --ansi --no-interaction
-RUN chown -R www-data:www-data /var/www/html/vendor
-# temporary copy of all code (except for vendor and node_modules), so that we can copy it to /var/www/html (see below)
-# remove those dependencies to not interfier any dev changes in those dirs
-COPY --chown=www-data:www-data . /var/www/temp
-RUN rm -rfv /var/www/temp/vendor \
-    && rm -rfv /var/www/temp/node_modules \
-    # @see https://askubuntu.com/a/86891
-    && cp -a /var/www/temp/. /var/www/html/ \
-    && rm -rfv /var/www/temp
-
-##
-## Node Build Tools
-##
-ENV NODE_ENV="development"
-RUN npm config list \
-    && npm install --only=development \
-    && npm run prod \
-    && npm cache clean --force
-
-# https://docs.npmjs.com/cli/v7/commands/npm-audit
-# RUN npm audit
-# TODO think of security checker @see https://github.com/FriendsOfPHP/security-advisories
-# TODO think of running `composer validate` or `composer outdated` or `composer diagnose`
-
-RUN wget https://github.com/aquasecurity/trivy/releases/download/v0.20.2/trivy_0.20.2_Linux-64bit.deb
-RUN dpkg -i trivy_0.20.2_Linux-64bit.deb \
-    && trivy filesystem --exit-code 0 --no-progress /
-
-
-
-### Pre production stage ###
-## is used to not bloat prod image
-## recomenned by Bret Fisher for avoiding put deleted unnecessary files in prod
-FROM test as pre-prod
-
-# delete unused in production files
-# node_modules / css / js and images are compiled to ./public
-RUN rm -rfv /var/www/html/tests \
-    && rm -rfv /var/www/html/trivy_* \
-    && rm -rfv /var/www/html/node_modules \
-    && rm -rfv /var/www/html/resources/css \
-    && rm -rfv /var/www/html/resources/js \
-    && rm -rfv /var/www/html/resources/images \
-    && rm -rfv /var/www/html/resources/fonts \
-    # todo think if we need to remove non-persistent data manually
-    && rm -rfv /var/www/html/bootstrap/cache/data/* \
-    && rm -rfv /var/www/html/storage/logs/* \
-    && rm -rfv /var/www/html/storage/media-library/temp/* \
-    && rm -rfv /var/www/html/storage/debugbar/* \
-    && rm -rfv /var/www/html/storage/framework/sessions/* \
-    && rm -rfv /var/www/html/storage/framework/views/* \
-
-    && rm -rfv /var/www/html/storage/framework/testing/*
-
-
-
-### Prod stage ###
-FROM dependencies as prod
-
-### copy entrypoint and overwrite default one of base php image ###
-COPY ./docker/app/docker-php-entrypoint-prod /usr/local/bin/
-RUN dos2unix /usr/local/bin/docker-php-entrypoint-prod \
-    && chmod 770 /usr/local/bin/docker-php-entrypoint-prod
-
-ENTRYPOINT ["docker-php-entrypoint-prod"]
-
-# we already have node_modules / tests / resources/(css|js) / storage in base
-# so we copy from pre-prod without those of 'test' stage
-COPY --from=pre-prod --chown=www-data:www-data /var/www/html /var/www/html
-
-# be sure nginx is properly passing to php-fpm and fpm is responding
-#HEALTHCHECK --interval=5s --timeout=3s CMD curl -f "http://localhost$FPM_PING_URI" || exit 1
-
-# 80 - for nginx
-EXPOSE 80
-
-##
-## Configuration of supervisord, php and nginx
-##
-# supervisord config
-COPY ./docker/app/supervisord.conf /etc/supervisord.conf
-
-CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
-
-
-# TODO think of adding base auth for $FPM_PING_URI $FPM_STATUS_URI $NGINX_STATUS_URI pages
-#RUN /bin/bash -c "htpasswd -bn default secret > /etc/nginx/conf.d/nginx.htpasswd"
-#COPY ./docker/app/nginx.htpasswd /etc/nginx/conf.d/nginx.htpasswd
+RUN dos2unix /etc/supervisord.conf
