WIP

diff --git a/app/Dockerfile b/app/Dockerfile
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -1,34 +1,60 @@
-# Multistage dockerfile
-# always pin the version
-FROM php:8.0.11-fpm as base
+FROM php:8.0.12-fpm-buster
 
-# nginx env (copied from official nginx dockerfile)
-# @see https://github.com/nginxinc/docker-nginx/blob/f3fe494531f9b157d9c09ba509e412dace54cd4f/stable/debian/Dockerfile
+### BASE PART of image ###
 ENV NGINX_VERSION=1.20.1 \
-    PKG_RELEASE=1~buster \
     NJS_VERSION=0.5.3 \
-# node env (copied from official node dockerfile)
-# @see https://github.com/nodejs/docker-node/blob/a70c43d47528213ef0cd58af7c35edf4c1d3e990/14/buster-slim/Dockerfile
-    NODE_VERSION=14.18.1 \
-# general env
-    APP_DIR="/var/www/html"
+    PKG_RELEASE=1~buster
 
-# install apt dependencies
 RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y \
-        wget \
-        curl \
-        bash \
-        supervisor \
-        git && \
-        rm -r /var/lib/apt/lists/* && \
-# install php extensions
-# using mlocati/docker-php-extension-installer recomended by official php docker repo
-# @see https://github.com/docker-library/docs/blob/master/php/README.md#php-core-extensions
-    curl -sSLf \
-        -o /usr/local/bin/install-php-extensions \
-        https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions && \
-        chmod +x /usr/local/bin/install-php-extensions && \
-        install-php-extensions \
+    curl \
+    wget \
+    bash \
+    supervisor \
+    git \
+    dos2unix \
+    # need for nginx
+    gnupg1 \
+    ca-certificates \
+    && rm -r /var/lib/apt/lists/* \
+    # install nginx (copied from official nginx Dockerfile)
+    && NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
+        found=''; \
+        for server in \
+            ha.pool.sks-keyservers.net \
+            hkp://keyserver.ubuntu.com:80 \
+            hkp://p80.pool.sks-keyservers.net:80 \
+            pgp.mit.edu \
+        ; do \
+            echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
+            apt-key adv --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
+        done; \
+
+        test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
+        apt-get remove --purge --auto-remove -y gnupg1 && rm -rf /var/lib/apt/lists/* \
+        && dpkgArch="$(dpkg --print-architecture)" \
+        && nginxPackages=" \
+            nginx=${NGINX_VERSION}-${PKG_RELEASE} \
+            nginx-module-xslt=${NGINX_VERSION}-${PKG_RELEASE} \
+            nginx-module-geoip=${NGINX_VERSION}-${PKG_RELEASE} \
+            nginx-module-image-filter=${NGINX_VERSION}-${PKG_RELEASE} \
+            nginx-module-njs=${NGINX_VERSION}+${NJS_VERSION}-${PKG_RELEASE} \
+        " \
+        && echo "deb https://nginx.org/packages/debian/ buster nginx" >> /etc/apt/sources.list.d/nginx.list \
+        && apt-get update \
+        && apt-get install --no-install-recommends --no-install-suggests -y \
+            $nginxPackages \
+            gettext-base \
+            curl \
+        && apt-get remove --purge --auto-remove -y && rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/nginx.list \
+        # forward request and error logs to docker log collector
+        && ln -sf /dev/stdout /var/log/nginx/access.log \
+        && ln -sf /dev/stderr /var/log/nginx/error.log \
+    # install php extensions
+    # using mlocati/docker-php-extension-installer recomended by official php docker repo
+    # @see https://github.com/docker-library/docs/blob/master/php/README.md#php-core-extensions
+    && curl -sSLf -o /usr/local/bin/install-php-extensions https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
+        && chmod +x /usr/local/bin/install-php-extensions \
+        && install-php-extensions \
             pdo_mysql \
             mysqli \
             json \
@@ -41,56 +67,128 @@ RUN apt-get update && apt-get install --no-install-recommends --no-install-sugge
             xml \
             exif \
             bcmath \
-            pcntl
+            pcntl \
+            xdebug \
+            gmagick \
+            imagick
+# install composer from official image
+COPY --from=composer:2.1.9 /usr/bin/composer /usr/bin/composer
+
+## install node and yarn: copied from official node docker image
+# LTS version of node
+ENV NODE_VERSION 14.18.1
+
+RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" \
+    && case "${dpkgArch##*-}" in \
+        amd64) ARCH='x64';; \
+        ppc64el) ARCH='ppc64le';; \
+        s390x) ARCH='s390x';; \
+        arm64) ARCH='arm64';; \
+        armhf) ARCH='armv7l';; \
+        i386) ARCH='x86';; \
+        *) echo "unsupported architecture"; exit 1 ;; \
+    esac \
+    # gpg keys listed at https://github.com/nodejs/node#release-keys
+    && set -ex \
+    && for key in \
+        4ED778F539E3634C779C87C6D7062848A1AB005C \
+        94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
+        74F12602B6F1C4E913FAA37AD3A89613643B6201 \
+        71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
+        8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600 \
+        C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
+        C82FA3AE1CBEDC6BE46B9360C43CEC45C17AB93C \
+        DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
+        A48C2BEE680E841632CD4E44F07496B3EB3C1762 \
+        108F52B48DB57BB0CC439B2997B01419BD92F80A \
+        B9E2F5981AA6E0CD28160D9FF13993A75599653C \
+    ; do \
+        gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys "$key" || \
+        gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key" ; \
+    done \
+    && curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$ARCH.tar.xz" \
+    && curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
+    && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
+    && grep " node-v$NODE_VERSION-linux-$ARCH.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
+    && tar -xJf "node-v$NODE_VERSION-linux-$ARCH.tar.xz" -C /usr/local --strip-components=1 --no-same-owner \
+    && rm "node-v$NODE_VERSION-linux-$ARCH.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt \
+    && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
+    # smoke tests
+    && node --version \
+    && npm --version
+
+ENV YARN_VERSION 1.22.15
+
+RUN set -ex \
+    && for key in \
+        6A010C5166006599AA17F08146C2130DFD2497F5 \
+    ; do \
+        gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys "$key" || \
+        gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key" ; \
+    done \
+    && curl -fsSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz" \
+    && curl -fsSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz.asc" \
+    && gpg --batch --verify yarn-v$YARN_VERSION.tar.gz.asc yarn-v$YARN_VERSION.tar.gz \
+    && mkdir -p /opt \
+    && tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ \
+    && ln -s /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn \
+    && ln -s /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg \
+    && rm yarn-v$YARN_VERSION.tar.gz.asc yarn-v$YARN_VERSION.tar.gz \
+    # smoke test
+    && yarn --version
 
 
 
+# add custom php-fpm pool settings, these get written at entrypoint startup
+ENV FPM_PM_MAX_CHILDREN=20 \
+    FPM_PM_START_SERVERS=2 \
+    FPM_PM_MIN_SPARE_SERVERS=1 \
+    FPM_PM_MAX_SPARE_SERVERS=3 \
+    FPM_PING_URI='/---ping' \
+    FPM_STATUS_URI='/---status' \
+    NGINX_STATUS_URI='/---status-nginx' \
+    NGINX_READ_TIMEOUT=60 \
+    XDEBUG_TRIGGER='PHPSTORM'
 
-FROM base as dev
-## TODO think of adding yarn
-## add xdebug
-# install-php-extensions xdebug
+### php-fpm config ###
+COPY ./docker/app/zzz-app.conf /tmp/zzz-app.conf
+# name of the file is `zzz-app.conf`, so that the directive in /usr/local/etc/php-fpm.conf `include=etc/php-fpm.d/*.conf`
+# would include zzz-app.conf file as the latest and according php-fpm configuration overwrite any previous config files
+RUN envsubst '$FPM_PM_MAX_CHILDREN $FPM_PM_START_SERVERS $FPM_PM_MIN_SPARE_SERVERS $FPM_PM_MAX_SPARE_SERVERS $FPM_PING_URI $FPM_STATUS_URI' < /tmp/zzz-app.conf > /usr/local/etc/php-fpm.d/zzz-app.conf
 
+# Use the default production configuration
+# TODO temporary
+RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
 
+# custom php.ini
+COPY ./docker/app/php.ini /tmp/zzz-php.ini
+RUN envsubst '$XDEBUG_TRIGGER' < /tmp/zzz-php.ini > "$PHP_INI_DIR/conf.d/zzz-php.ini"
 
+### nginx config ###
+COPY ./docker/app/nginx.conf /etc/nginx/nginx.conf
+COPY ./docker/app/nginx-site.conf /tmp/nginx-site.conf
+RUN envsubst '$FPM_PING_URI $FPM_STATUS_URI $NGINX_STATUS_URI $NGINX_READ_TIMEOUT' < /tmp/nginx-site.conf > /etc/nginx/conf.d/default.conf
 
+# TODO temporary decision
+#RUN /bin/bash -c "htpasswd -bn default secret > /etc/nginx/conf.d/nginx.htpasswd"
+#COPY ./docker/app/nginx.htpasswd /etc/nginx/conf.d/nginx.htpasswd
 
+### supervisord config ###
+COPY ./docker/app/supervisord.conf /etc/supervisord.conf
 
-# Install Composer
-RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
+# copy in app code as late as possible, as it changes the most
+COPY --chown=www-data:www-data ./public /var/www/html/public
+RUN chown -R :www-data /var/www/html/public
+RUN chmod -R g+w /var/www/html/public
 
-# Optional, force UTC as server time
-RUN echo "UTC" > /etc/timezone
+# be sure nginx is properly passing to php-fpm and fpm is responding
+HEALTHCHECK --interval=5s --timeout=3s CMD curl -f "http://localhost$FPM_PING_URI" || exit 1
 
+WORKDIR /var/www/html
 
+# 80 - for nginx
+# 9000 - for php
+# 9001 - for php debug
+EXPOSE 80 9000 9001 9003
 
-
-
-
-
-# node
-ENV NODE_VERSION=14.17.6
-RUN apt install -y curl
-RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
-ENV NVM_DIR=/root/.nvm
-RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
-RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
-RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
-ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
-RUN node --version
-RUN npm --version
-
-WORKDIR /etc
-
-COPY supervisord.conf /etc/supervisord.conf
-
-
-# Clean up
-RUN apt-get remove -y git && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
-
-WORKDIR $APP_DIR
-
-
-ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
-
-EXPOSE 9000
+CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
